# Usar una imagen base de Python
FROM python:3.8

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos y tu aplicación al contenedor
COPY requirements.txt /app/
COPY . /app/

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que Flask se ejecutará
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
